### ISSUE TITLE
Objectify 6.1.x breaks serializaton of entities

### ISSUE THREAD

**Issue by dietl-conrad** [objectify/objectify#504]
When upgrading to 6.1.x from 6.0.x it is not possible anymore to serialize entities with Ref fields. The class com.googlecode.objectify.Ref does not implement the Serializable interface anymore. What's the reason for it and how to solve the problem?

`org.apache.commons.lang3.SerializationException: java.io.NotSerializableException: com.googlecode.objectify.Ref
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:266)
	at org.apache.commons.lang3.SerializationUtils.serialize(SerializationUtils.java:241)
	at org.apache.commons.lang3.SerializationUtils.clone(SerializationUtils.java:139)
`

**Comment by stickfigure** [comment]
Correct. This is covered in https://github.com/objectify/objectify/wiki/UpgradeVersion6ToVersion61

There's no good way around this, we have to remove serializability of Ref<?>s, so the bandaid has to be pulled off eventually. The best solution is to migrate data so you aren't serializing Refs. There are probably ways of kicking the can down the road by tricking the serialization system, but the data will have to be migrated eventually.
