### ISSUE TITLE
I got java.lang.NoSuchMethodError after updating to 4.03b.

### ISSUE THREAD

**Issue by AlQuraian** [objectify/objectify#6]
This is the error:
Caused by: java.lang.NoSuchMethodError: com.googlecode.objectify.cmd.Query.first()Lcom/googlecode/objectify/LoadResult;

I only updated to the latest one cause version 4.2b (for some odd reason) doesn't have the now() method when loading an entity.

Should I provide more info?
